### ISSUE TITLE
error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Ran0618** [IDEA-Research/Grounded-SAM-2#71]
When using SAM2, I encountered this issue, and after consulting the documentation, I found that I needed to `export TORCH_CUDA_ARCH_LIST=9.0 8.0 8.6 8.9 7.0 7.2 7.5 6.0`. However, this did not resolve the problem.

I discovered that the GroundingDINO part of the code works successfully, so I tried to identify the issue. I found that the problem lies in the `groundingdino/setup.py` file:

```
extra_compile_args["nvcc"] = [
    "-DCUDA_HAS_FP16=1",
    "-D__CUDA_NO_HALF_OPERATORS__",
    "-D__CUDA_NO_HALF_CONVERSIONS__",
    "-D__CUDA_NO_HALF2_OPERATORS__",
    "-gencode=arch=compute_70,code=sm_70",
    "-gencode=arch=compute_75,code=sm_75",
    "-gencode=arch=compute_80,code=sm_80",
    "-gencode=arch=compute_86,code=sm_86",
]
```
In this code, there is no entry for CUDA capability 9.0, so when using a GPU with capability 9.0 and following the official installation procedure, it would throw an error. The solution is to add the line `-gencode=arch=compute_90,code=sm_90` to the `extra_compile_args["nvcc"]` section.

**Comment by suhyeok-jang** [comment]
it's really helpful. Thank you

**Comment by winter-fish** [comment]
This is incredibly helpful！🙏

**Comment by qyr0403** [comment]
It is useful for NVIDIA-H20 GPU! thank you

**Comment by Unc1eW4ng** [comment]
What's the version of your nvidia driver and nvcc ? the 'ms_deformable_im2col_cuda' error still appeared  after i modified the setup.py and reinstall groundingdino.Thanks

**Comment by ZixuanNi** [comment]
> it works for H100-80G

May I ask what specific parameters you added? After I set it to '-gencode=arch=compute_90,code=sm_90', it still doesn't work.

**Comment by Unc1eW4ng** [comment]
> > it works for H100-80G
> 
> May I ask what specific parameters you added? After I set it to '-gencode=arch=compute_90,code=sm_90', it still doesn't work.

After updating the parameters and before you reinstall the package, you need to ensure that the dir 'build' is removed, which may be reused and would not be compiled with new parameters.

**Comment by zc-alexfan** [comment]
https://github.com/IDEA-Research/Grounded-SAM-2/issues/71#issuecomment-2834498001

This works for me. Just to be entirely sure. I removed the repo and git clone from scratch.

**Comment by tansangxtt** [comment]
I got the same error on Jetson AGX Orin, to make it work 
update ```Grounded-SAM-2/grounding_dino/setup.py```, ```Grounded-SAM-2/setup.py```
```python
-gencode=arch=compute_87,code=sm_87
``` 
added to extra_compile_args["nvcc"]
